source 'https://rubygems.org'

gem 'attr_extras'
gem 'bcrypt'
gem 'dry-core'
gem 'dry-inflector'
gem 'dry-monads'
gem 'dry-schema'
gem 'dry-system'
gem 'dry-transformer'
gem 'dry-types'
gem 'dry-validation'
gem 'falcon'
gem 'faraday'
gem 'i18n'
gem 'jwt'
gem 'mail'
gem 'pg'
gem 'rack-cors'
gem 'rake'
gem 'roda'
gem 'rodauth'
gem 'rom'
gem 'rom-sql'
gem 'sequel'
gem 'sequel_pg'

group :development do # rubocop:disable Metrics/BlockLength
  gem 'bundler-audit'
  gem 'database_cleaner-sequel'
  gem 'factory_bot'
  gem 'faker'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'rack-test'
  gem 'rerun'
  gem 'rspec'
  gem 'rspec-collection_matchers'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  # gem 'rubocop-sequel'
  # gem 'rubycritic'
  gem 'ruby_jard'
  gem 'simplecov'
  gem 'sqlite3'
  # gem 'super_diff'
  gem 'timecop'
  gem 'webmock'
end
