source 'https://rubygems.org'

gem 'attr_extras'
gem 'dry-monads'
gem 'dry-schema'
gem 'dry-system'
gem 'dry-types'
gem 'falcon'
gem 'pg'
gem 'rack-cors'
gem 'rake'
gem 'roda'
gem 'sequel'

group :development do
  gem 'database_cleaner-sequel'
  gem 'factory_bot'
  gem 'faker'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'rack-test'
  gem 'rerun'
  gem 'rspec'
  gem 'rspec-collection_matchers'
  gem 'rubocop'
  gem 'simplecov'
end
