inherit_from:
  - ../.rubocop.yml

inherit_mode:
  merge:
    - IgnoredMethods

Metrics/BlockLength:
  Max: 100

RSpec/ExampleLength:
  Max: 20

RSpec/Capybara/FeatureMethods:
  EnabledMethods: [feature]

RSpec/ContextWording:
  Enabled: false

RSpec/FactoryBot/FactoryClassName:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NestedGroups:
  Max: 4

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - be
    - be_a
    - describe
    - eq
    - header
    - feature
    - include
    - match
    - not_to
    - post_json
    - raise_exception
    - subject
    - to

RSpec/ScatteredLet:
  Enabled: false
