inherit_from:
  - ../.rubocop.yml

inherit_mode:
  merge:
    - IgnoredMethods

Capybara/FeatureMethods:
  EnabledMethods: [feature]

FactoryBot/FactoryClassName:
  Enabled: false

Metrics/BlockLength:
  Max: 100

RSpec/ExampleLength:
  Max: 15

RSpec/ContextWording:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NestedGroups:
  Max: 4

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - be
    - be_a
    - describe
    - eq
    - feature
    - include
    - match
    - not_to
    - raise_exception
    - subject
    - to
