require_relative 'helpers/configuration'
require_relative 'helpers/time_slots'
require_relative 'helpers/exam_types'
require_relative 'helpers/registrations'
require_relative 'helpers/authentication'
